### ISSUE TITLE
bad code 

### ISSUE THREAD

**Issue by NSXC** [boi458nose/Cookie-Checker#1]
Error handling is missing, so it might be difficult to identify and handle specific errors if they occur no try very bad 
The indentation is inconsistent, making it a bit harder to follow the flow of the code.

The command-line screen clearing method used (os.system("cls")) may not work on all platforms. It's better to use platform-specific commands for better portability and this is only works on windows 0 support for mac or linux wth

The user input for the cookie is not validated, which can pose security risks. It's important to validate and sanitize user input.

The code lacks modularity and could benefit from being divided into separate functions or classes for better organization and reusability.

String formatting is mixed, combining concatenation and f-strings. It's recommended to stick to one consistent approach, preferably f-strings.

Redundant use of bool() in an if condition can be simplified by evaluating the value directly fix this

**Comment by I458I** [comment]
Put it on Emmet till SOUL
